### PR TITLE
FieldArray over v3/reducer-refs

### PR DESCRIPTION
**Pull request by johnrom**

### CODE REVIEW

**Comment by johnrom** [comment]
I removed the ability for FieldArray to print a simple input, because it doesn't actually pass any of the correct props for that to work. For it to print an array of simple inputs, it'd have to do something like:

```tsx
typeof component === "string" ? field.value.map((value, index) => {
  const inputProps = {
    ...selectInputProps(props, index),
    ...rest
  };

  return React.createElement(component, inputProps);
}
```

And I don't think that's actually going to work for anyone in real life. Where are the labels? Error messages? etc.

**Comment by RealDrewKlayman** [comment]
Any update on this PR?

**Comment by johnrom** [comment]
I'll redo this over v3 against a different branch once v3 is further along.

**Comment by johnrom** [comment]
closed in favor of https://github.com/formium/formik/pull/3123

**Pull request closed without merging**
